// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleChatApi.Data;

#nullable disable

namespace SimpleChatApi.Migrations
{
    [DbContext(typeof(ChatContext))]
    partial class ChatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("SimpleChatApi.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatorChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatorChatId = 1,
                            Name = "NewChat_1"
                        },
                        new
                        {
                            Id = 2,
                            CreatorChatId = 2,
                            Name = "NewChat_2"
                        },
                        new
                        {
                            Id = 3,
                            CreatorChatId = 3,
                            Name = "NewChat_3"
                        });
                });

            modelBuilder.Entity("SimpleChatApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Elon"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kate"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dan"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chuck"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Julia"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Juliet"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Bart"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Blair"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Nat"
                        });
                });

            modelBuilder.Entity("SimpleChatApi.Models.UserChat", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "ChatId");

                    b.HasIndex("ChatId");

                    b.ToTable("UserChats");
                });

            modelBuilder.Entity("SimpleChatApi.Models.UserChat", b =>
                {
                    b.HasOne("SimpleChatApi.Models.Chat", "Chat")
                        .WithMany("UserChats")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleChatApi.Models.User", "User")
                        .WithMany("UserChats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SimpleChatApi.Models.Chat", b =>
                {
                    b.Navigation("UserChats");
                });

            modelBuilder.Entity("SimpleChatApi.Models.User", b =>
                {
                    b.Navigation("UserChats");
                });
#pragma warning restore 612, 618
        }
    }
}
